# Generated by Django 4.0.4 on 2022-05-21 07:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('birthday', models.DateField(blank=True, default='21/05/2004')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('imageCustomer', models.ImageField(blank=True, default='no_image.png', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100)),
                ('plate', models.CharField(default='', max_length=7, unique=True)),
                ('yearCar', models.IntegerField(default='')),
                ('marketVal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('imageCar', models.ImageField(blank=True, default='no_image.png', null=True, upload_to='media')),
                ('description', models.CharField(default='', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
            ],
        ),
    ]
