# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 00:23
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default=b'', max_length=100)),
                ('plate', models.CharField(default=b'', max_length=7, unique=True)),
                ('yearCar', models.IntegerField(default=b'')),
                ('marketVal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('imageCar', models.ImageField(blank=True, default=b'no_image.png', null=True, upload_to=b'media')),
                ('description', models.CharField(default=b'', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('email', models.EmailField(default=b'', max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('birthday', models.DateField(blank=True, default=b'26/06/1999')),
                ('gender', models.CharField(choices=[(b'M', b'MALE'), (b'F', b'FEMALE')], default=b'M', max_length=1)),
                ('imageCustomer', models.ImageField(blank=True, default=b'no_image.png', null=True, upload_to=b'media')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.Customer'),
        ),
    ]
